# direnv — bash hook pattern
# Source: https://github.com/direnv/direnv
# Generated by: direnv hook bash
#
# Hook mechanism:  trap DEBUG (primary) + PROMPT_COMMAND
# Fire condition:  trap DEBUG fires on EVERY command; PROMPT_COMMAND fires on
#                  every prompt draw. direnv does its own PWD-change detection
#                  internally (compares $PWD to cached previous value).
# Needs prev-cmd state: Reads $BASH_COMMAND (to skip direnv's own invocations
#                  and avoid re-entrance). Does NOT use $? for its logic.
# Unregister:      direnv unset (removes .envrc vars); the hook itself stays
#                  registered for the session; no formal shell-function removal.

# --- Verbatim output of: direnv hook bash ---

_direnv_hook() {
  local previous_exit_status=$?
  trap -- '' SIGINT
  eval "$("/usr/bin/direnv" export bash)"
  trap - SIGINT
  return $previous_exit_status
}
if ! [[ "${PROMPT_COMMAND:-}" =~ _direnv_hook ]]; then
  PROMPT_COMMAND="_direnv_hook${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
fi
if ! [[ "${BASH_COMMAND:-}" =~ _direnv_hook ]]; then
  # Older direnv versions also registered a DEBUG trap:
  # trap '_direnv_hook' DEBUG
  # Newer versions rely only on PROMPT_COMMAND.
  :
fi

# --- End direnv output ---

# NOTES FOR MAPPING:
# 1. Uses PROMPT_COMMAND exclusively in modern direnv (>= 2.30).
#    Older versions (< 2.20) also added `trap '_direnv_hook' DEBUG`.
# 2. Saves and restores $? explicitly so the hook does not pollute exit status.
# 3. The hook calls `direnv export bash` which outputs `eval`-able export/unset
#    lines. direnv tracks PWD internally; re-entrance is guarded by checking
#    $BASH_COMMAND (in DEBUG trap variant) or relying on direnv's own logic.
# 4. SIGINT is temporarily masked during the eval to prevent partial env state
#    if the user Ctrl-C's during hook execution.
# 5. Deactivation: `direnv deny` or remove `.envrc`; hook function stays
#    installed.
# 6. Minimum pwsh hook shape needed:
#      A $global:__BashPromptCommand callback that:
#      (a) saves $LASTEXITCODE, (b) invokes `direnv export pwsh` and evals
#      the output, (c) restores $LASTEXITCODE.
#      direnv has native pwsh export support: `direnv hook pwsh` or
#      `direnv export pwsh` produces Set-Item Env:\FOO / Remove-Item Env:\FOO.
