# fnm (Fast Node Manager) — bash hook pattern
# Source: https://github.com/Schniz/fnm
# Generated by: fnm env --shell bash --use-on-cd
#
# Hook mechanism:  PROMPT_COMMAND (with --use-on-cd) or eval of bare fnm env
# Fire condition:  Every prompt draw (PROMPT_COMMAND fires on every command,
#                  but fnm internally tracks $PWD and no-ops when unchanged)
# Needs prev-cmd state: No ($BASH_COMMAND not used; $? not consulted)
# Unregister:      Remove the fnm-added function from PROMPT_COMMAND; no
#                  formal deactivation API — user must re-source without --use-on-cd

# --- Verbatim output of: fnm env --shell bash --use-on-cd ---

export PATH="/home/user/.local/share/fnm:$PATH"
export FNM_VERSION_FILE_STRATEGY="local"
export FNM_DIR="/home/user/.local/share/fnm"
export FNM_LOGLEVEL="info"
export FNM_NODE_DIST_MIRROR="https://nodejs.org/dist"
export FNM_COREPACK_ENABLED="false"
export FNM_RESOLVE_ENGINES="false"
export FNM_ARCH="x64"
export FNM_OS="linux"

# The --use-on-cd hook is the key piece:
fnm_auto_use() {
  if [[ -f .node-version || -f .nvmrc ]]; then
    fnm use --silent-if-unchanged
  fi
}

# Appended to PROMPT_COMMAND (not trap DEBUG):
if [[ ":${PROMPT_COMMAND}:" != *":fnm_auto_use:"* ]]; then
  PROMPT_COMMAND="fnm_auto_use${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
fi

# --- End fnm output ---

# NOTES FOR MAPPING:
# 1. No trap DEBUG — purely PROMPT_COMMAND.
# 2. PWD-change detection is internal to `fnm use --silent-if-unchanged`
#    (fnm reads $PWD on each call and compares to last-seen dir).
# 3. The hook shell function calls an external binary (`fnm use`); it is not
#    pure shell arithmetic.
# 4. Deactivation: unset fnm_auto_use; remove from PROMPT_COMMAND manually.
# 5. Minimum pwsh hook shape needed:
#      $env:PATH updated on shell init + a callback registered in
#      $global:__BashPromptCommand that calls `fnm use --silent-if-unchanged`
#      on every prompt (or on $PWD change detection in the wrapper).
