# nodenv — bash hook pattern
# Source: https://github.com/nodenv/nodenv
# Generated by: nodenv init - (or nodenv init - bash)
#
# Hook mechanism:  PROMPT_COMMAND + rehash shim stub
# Fire condition:  PROMPT_COMMAND fires on every prompt draw. nodenv does NOT
#                  do automatic version-switching on cd; it only rehashes shims.
#                  The actual version is resolved per-invocation via shim lookup.
# Needs prev-cmd state: No ($BASH_COMMAND not used, $? not consulted)
# Unregister:      Remove nodenv from $PATH; shims resolution stops. No explicit
#                  deactivation command.

# --- Representative output of: nodenv init - bash ---

export PATH="/home/user/.nodenv/shims:${PATH}"
export NODENV_SHELL=bash

# Rehash shims after every command that may have installed new executables:
_nodenv_prompt_hook() {
  nodenv rehash 2>/dev/null
}
if [[ ! "${PROMPT_COMMAND:-}" =~ _nodenv_prompt_hook ]]; then
  PROMPT_COMMAND="_nodenv_prompt_hook${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
fi

# Also defines the `nodenv` shell function (overrides the binary) to handle
# `nodenv shell <version>` (sets NODENV_VERSION env var in current shell):
nodenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(nodenv "sh-$command" "$@")";;
  *)
    command nodenv "$command" "$@";;
  esac
}

# --- End nodenv output ---

# NOTES FOR MAPPING:
# 1. No trap DEBUG — PROMPT_COMMAND only.
# 2. Version switching on cd is NOT built-in to nodenv init. The version is
#    read from .node-version / .nodenv-version by the shim itself at invocation
#    time. No per-cd hook is needed for version resolution.
# 3. PROMPT_COMMAND hook only does `nodenv rehash` to regenerate shims after
#    package installs.
# 4. The `nodenv` shell function intercepts `rehash` and `shell` subcommands
#    to allow eval of output in the current shell (for NODENV_VERSION export).
# 5. Minimum pwsh hook shape needed:
#      Prepend shims dir to $env:PATH; define a `nodenv` function that evals
#      sh-rehash/sh-shell output; optionally run `nodenv rehash` in
#      $global:__BashPromptCommand.
