# pyenv — bash hook pattern
# Source: https://github.com/pyenv/pyenv
# Generated by: pyenv init - (or pyenv init - bash)
#
# Hook mechanism:  PROMPT_COMMAND + shell function + shims
# Fire condition:  PROMPT_COMMAND fires on every prompt draw (for rehash).
#                  Version NOT switched on cd — resolved per-invocation via shims.
# Needs prev-cmd state: No ($BASH_COMMAND not used; $? saved and restored but
#                  not inspected for logic)
# Unregister:      Remove pyenv shims/bin from $PATH; unset PYENV_ROOT.

# --- Representative output of: eval "$(pyenv init -)" ---

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/shims:$PATH"
export PYENV_SHELL=bash

# Source completions if available:
# source "${PYENV_ROOT}/completions/pyenv.bash"

_pyenv_virtualenv_hook() {
  local ret=$?
  if [ -n "$VIRTUAL_ENV" ]; then
    eval "$(pyenv sh-activate --quiet || true)" 2>/dev/null
  else
    eval "$(pyenv sh-deactivate --quiet || true)" 2>/dev/null
  fi
  return $ret
}

# pyenv-virtualenv plugin (if installed) uses PROMPT_COMMAND for venv switching:
if [[ ! "${PROMPT_COMMAND:-}" =~ _pyenv_virtualenv_hook ]]; then
  PROMPT_COMMAND="_pyenv_virtualenv_hook${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
fi

# The core pyenv shell function (intercepts sh-subcommands):
pyenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  activate|deactivate|rehash|shell)
    eval "$(pyenv "sh-$command" "$@")";;
  *)
    command pyenv "$command" "$@";;
  esac
}

# --- End pyenv output ---

# NOTES FOR MAPPING:
# 1. Base pyenv: no PROMPT_COMMAND hook — only shims + shell function.
# 2. pyenv-virtualenv plugin adds a PROMPT_COMMAND hook for venv activation.
# 3. No trap DEBUG anywhere in the pyenv ecosystem.
# 4. `pyenv shell <version>` sets PYENV_VERSION via eval in current shell.
# 5. `pyenv activate <env>` (virtualenv plugin) sets VIRTUAL_ENV via eval.
# 6. Version resolution is per-invocation (shim reads .python-version).
# 7. Minimum pwsh hook shape needed:
#      Shims in $env:PATH; pyenv shell function for sh-subcommands; optional
#      prompt hook for virtualenv switching (eval `pyenv sh-activate` output).
