# rbenv — bash hook pattern
# Source: https://github.com/rbenv/rbenv
# Generated by: rbenv init - (or rbenv init - bash)
#
# Hook mechanism:  PROMPT_COMMAND + shell function wrapping rbenv binary
# Fire condition:  PROMPT_COMMAND fires on every prompt draw (for rehash only).
#                  Version resolution is per-invocation via shims, NOT on cd.
# Needs prev-cmd state: No ($BASH_COMMAND not used, $? not consulted)
# Unregister:      Remove rbenv shims from $PATH; no explicit deactivate.

# --- Representative output of: rbenv init - bash ---

export PATH="/home/user/.rbenv/shims:${PATH}"
export RBENV_SHELL=bash
source '/home/user/.rbenv/libexec/../completions/rbenv.bash'

# Rehash on every prompt:
_rbenv_prompt_hook() {
  local ret=$?
  rbenv rehash 2>/dev/null
  return $ret
}
if [[ ! "${PROMPT_COMMAND:-}" =~ _rbenv_prompt_hook ]]; then
  PROMPT_COMMAND="_rbenv_prompt_hook${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
fi

# Shell function to intercept `rbenv shell` and `rbenv rehash`:
rbenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(rbenv "sh-$command" "$@")";;
  *)
    command rbenv "$command" "$@";;
  esac
}

# --- End rbenv output ---

# NOTES FOR MAPPING:
# 1. Identical pattern to nodenv (rbenv is the inspiration; nodenv is a port).
# 2. No trap DEBUG — PROMPT_COMMAND only.
# 3. Version NOT switched on cd; .ruby-version is read by the shim at run time.
# 4. `rbenv shell <version>` sets RBENV_VERSION in current environment via eval.
# 5. PROMPT_COMMAND hook saves/restores $? to avoid polluting exit status.
# 6. Minimum pwsh hook shape needed:
#      Same as nodenv: shims in $env:PATH, rbenv function for sh-subcommands,
#      optional prompt hook for rehash.
