# starship — bash hook pattern
# Source: https://github.com/starship/starship
# Generated by: starship init bash
#
# Hook mechanism:  PROMPT_COMMAND (exclusive) — updates PS1 on every prompt
# Fire condition:  PROMPT_COMMAND fires after EVERY command to redraw the prompt.
#                  Starship reads $PWD, $?, $HISTCMD, git state, tool versions,
#                  etc. on each invocation. It does NOT gate on PWD change.
# Needs prev-cmd state: YES — reads $? (exit status of last command) and
#                  $HISTCMD (to distinguish a new command from a re-prompt);
#                  also reads timing via $STARSHIP_DURATION.
# Unregister:      Restore $PS1 / $PROMPT_COMMAND to saved values; unset
#                  starship shell functions. No single command does this.

# --- Representative output of: eval "$(starship init bash)" ---

# Starship needs to capture $? at the top of PROMPT_COMMAND before anything
# else resets it. It uses a pre-exec hook via DEBUG trap AND PROMPT_COMMAND.

__starship_precmd() {
    local __starship_exit_code=$?
    PS1="$(starship prompt --terminal-width="$COLUMNS" \
        --status="$__starship_exit_code" \
        --jobs="$(jobs -p | wc -l)")"
}

# For duration measurement, starship uses a DEBUG trap to capture the start
# time of each command:
__starship_preexec() {
    __STARSHIP_PROMPT_TIMER=${EPOCHREALTIME:-$(date +%s%3N)}
}
if [[ -z "${__starship_traps_installed:-}" ]]; then
    __starship_traps_installed=1
    # Install DEBUG trap for command timing:
    if [[ ! "${BASH_COMMAND:-}" =~ __starship_preexec ]]; then
        trap '__starship_preexec "$_"' DEBUG
    fi
    # Install PROMPT_COMMAND for prompt rendering:
    if [[ ! "${PROMPT_COMMAND:-}" =~ __starship_precmd ]]; then
        PROMPT_COMMAND="__starship_precmd${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
    fi
fi

# The preexec trap fires before each command to record start time;
# precmd fires after to render the prompt with elapsed duration:
__starship_precmd_full() {
    local __starship_exit_code=$?
    local __starship_duration=""
    if [[ -n "${__STARSHIP_PROMPT_TIMER:-}" ]]; then
        local __starship_now=${EPOCHREALTIME:-$(date +%s%3N)}
        # Duration passed as --cmd-duration flag in milliseconds:
        __starship_duration="$(((__starship_now - __STARSHIP_PROMPT_TIMER) * 1000))"
        unset __STARSHIP_PROMPT_TIMER
    fi
    PS1="$(starship prompt \
        --terminal-width="${COLUMNS:-}" \
        --status="${__starship_exit_code}" \
        --cmd-duration="${__starship_duration:-}" \
        --jobs="$(jobs -p | wc -l 2>/dev/null || echo 0)")"
}

# --- End starship output ---

# NOTES FOR MAPPING:
# 1. Uses BOTH trap DEBUG and PROMPT_COMMAND.
#    - DEBUG trap: fires before every command to record start time (preexec).
#    - PROMPT_COMMAND: fires after every command to render PS1 (precmd).
# 2. Captures $? at the VERY START of precmd (before any subcommand resets it).
# 3. Uses $EPOCHREALTIME (bash 5+) or `date +%s%3N` for millisecond timing.
# 4. Reads $COLUMNS (terminal width) on every prompt.
# 5. Does NOT gate on $PWD change — rerenders the full prompt on every command.
#    Git state, tool versions, etc. are read on every invocation by the external
#    `starship` binary (it manages its own caching internally).
# 6. Uses $BASH_COMMAND implicitly (guard to prevent trap re-entrance).
# 7. Unregister: `trap - DEBUG`; remove __starship_precmd from PROMPT_COMMAND;
#    restore $PS1 to a saved value.
# 8. Minimum pwsh hook shape needed:
#    A $global:__BashDebugTrap that records $EPOCHREALTIME or Get-Date before
#    each command; a $global:__BashPromptCommand that calls `starship prompt`
#    with --status=$LASTEXITCODE --cmd-duration=... and stores result in
#    $global:__BashPS1 / prompt function. The DEBUG trap hook is critical for
#    command duration; the PROMPT_COMMAND is critical for $?.
