# zoxide — bash hook pattern
# Source: https://github.com/ajeetdsouza/zoxide
# Generated by: zoxide init bash
#
# Hook mechanism:  Both PROMPT_COMMAND AND trap DEBUG (for __zoxide_pwd tracking)
# Fire condition:  trap DEBUG fires on EVERY command to capture $PWD before it
#                  changes; PROMPT_COMMAND fires after each command to add the
#                  new $PWD to the zoxide database.
# Needs prev-cmd state: Reads $PWD (not $BASH_COMMAND or $? for hook logic).
#                  The DEBUG trap captures $PWD *before* a `cd` runs; the
#                  PROMPT_COMMAND sees the new $PWD after.
# Unregister:      Unset the functions and remove from PROMPT_COMMAND/DEBUG trap.
#                  `zoxide init bash --no-cmd` can omit the `z`/`zi` aliases.

# --- Verbatim output of: zoxide init bash ---

# =============================================================================
#
# Utility functions for zoxide.
#

# pwd based on the value of _ZO_RESOLVE_SYMLINKS.
function __zoxide_pwd() {
    \builtin pwd -L
}

# A copy of fish's `status is-interactive` for bash/zsh.
function __zoxide_interactive() {
    return 0
}

# =============================================================================
#
# Hook configuration for zoxide.
#

# Hook to add new entries to the database.
if [[ ${_ZO_HOOK:-precmd} == 'pwd' ]]; then
    # Track $PWD changes via DEBUG trap:
    function __zoxide_hook() {
        \builtin local -r __zoxide_z_oldpwd="${__zoxide_oldpwd:-}"
        __zoxide_oldpwd="$(__zoxide_pwd)"
        if [[ ${__zoxide_z_oldpwd} != "${__zoxide_oldpwd}" ]]; then
            zoxide add -- "${__zoxide_oldpwd}"
        fi
    }
    if [[ -z "${__zoxide_hooked:-}" ]]; then
        __zoxide_hooked=1
        trap '__zoxide_hook' DEBUG
    fi
else
    # Default: use PROMPT_COMMAND (precmd mode)
    function __zoxide_hook() {
        zoxide add -- "$(__zoxide_pwd)"
    }
    if [[ -z "${__zoxide_hooked:-}" ]]; then
        __zoxide_hooked=1
        if [[ "${PROMPT_COMMAND:-}" != *'__zoxide_hook'* ]]; then
            PROMPT_COMMAND="${PROMPT_COMMAND:+${PROMPT_COMMAND};}__zoxide_hook"
        fi
    fi
fi

# =============================================================================
#
# When using ZO_HOOK=pwd (DEBUG trap mode), the hook compares the previous
# $PWD to the current one. In precmd (PROMPT_COMMAND) mode, it always adds
# the current directory — zoxide deduplicates internally.
#
# =============================================================================

# `z` command:
function z() {
    if [[ "$#" -eq 0 ]]; then
        __zoxide_z
    elif [[ "$#" -eq 1 && "$1" == '-' ]]; then
        __zoxide_z '-'
    elif [[ "$#" -eq 1 && -d "$1" ]]; then
        __zoxide_z "$1"
    elif [[ "${@: -1}" == "${_ZO_ECHO:=0}" ]]; then
        __zoxide_z "$@"
    else
        __zoxide_z "$@"
    fi
}

function __zoxide_z() {
    \builtin local result
    result="$(zoxide query -- "$@")" && __zoxide_cd "${result}"
}

function __zoxide_cd() {
    \builtin cd "$@" || \builtin return
}

# Interactive selection via `zi`:
function zi() {
    \builtin local result
    result="$(zoxide query -i -- "$@")" && __zoxide_cd "${result}"
}

# Aliases (unless --no-cmd):
alias cd='z'

# --- End zoxide output ---

# NOTES FOR MAPPING:
# 1. TWO hook modes:
#    a. PROMPT_COMMAND (default, _ZO_HOOK=precmd): runs `zoxide add` on every
#       prompt; no DEBUG trap; adds current dir unconditionally (dedup in db).
#    b. DEBUG trap (_ZO_HOOK=pwd): fires before EVERY command; compares $PWD to
#       previous value; only calls `zoxide add` on actual directory change.
# 2. In DEBUG trap mode, $PWD is captured before the command runs; the hook
#    fires when $PWD has already changed (next command after cd).
# 3. Does NOT read $BASH_COMMAND or $?
# 4. The `z` function wraps `zoxide query` then calls `cd` (or __zoxide_cd).
#    It overrides the `cd` alias entirely.
# 5. Unregister: `unset -f __zoxide_hook z zi __zoxide_z __zoxide_cd`;
#    remove from PROMPT_COMMAND; `trap - DEBUG`.
# 6. Minimum pwsh hook shape needed:
#    PROMPT_COMMAND mode: a callback in $global:__BashPromptCommand that calls
#    `zoxide add -- $PWD`. PWD hook mode: a $global:__BashDebugTrap callback
#    that compares $PWD to cached prev value. Also need to define the `z`
#    function as a PowerShell function.
